"use client";
import Link from "next/link";
import { Bell, Compass, Heart, Home, ImagePlus, Menu, MessageCircle, Search, Send, Settings, Users, X } from "lucide-react";
import { useState } from "react";
import { useCurrentUser } from "./useCurrentUser";
import type { Post } from "./homeData";
import styles from "./home.module.css";
const nav = [{href:"/",label:"Home",icon:Home},{href:"/messages",label:"Messages",icon:MessageCircle},{href:"/search",label:"Search",icon:Search},{href:"/discover",label:"Discover",icon:Compass},{href:"/profile",label:"Profile",icon:Users}];
const Avatar=({name}:{name:string})=><span className={styles.avatar}>{name.split(" ").map((p)=>p[0]).join("").slice(0,2)}</span>;
export function AppNav({query,onQueryChange}:{query?:string;onQueryChange?:(value:string)=>void}) { const user = useCurrentUser(); const name = user?.firstName || user?.displayName || user?.username || "Guest"; const [open,setOpen]=useState(false); return <><header className={styles.navbar}><button className={styles.menuTrigger} onClick={()=>setOpen(true)} aria-label="Open menu"><Menu size={21}/></button><Link href="/" className={styles.brand}><span>BC</span>boomchat</Link><nav>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href}><Icon size={18}/>{label}</Link>)}</nav><div className={styles.navTools}>{onQueryChange&&<label className={styles.navSearch}><Search size={17}/><input value={query} onChange={(e)=>onQueryChange(e.target.value)} placeholder="Search your community"/></label>}<button type="button" aria-label="Notifications"><Bell size={19}/></button><Link href="/profile"><Avatar name={name}/></Link></div></header><AppSidebar open={open} onClose={()=>setOpen(false)} name={name}/><nav className={styles.mobileNav}>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href}><Icon size={20}/><span>{label}</span></Link>)}</nav></>; }
export function AppSidebar({open,onClose,name}:{open:boolean;onClose:()=>void;name:string}) { return <><button className={`${styles.sidebarOverlay} ${open?styles.visible:""}`} onClick={onClose} aria-label="Close menu"/><aside className={`${styles.appSidebar} ${open?styles.sidebarOpen:""}`}><header><div><Avatar name={name}/><strong>{name}</strong></div><button onClick={onClose} aria-label="Close menu"><X size={19}/></button></header><nav>{nav.map(({href,label,icon:Icon})=><Link key={href} href={href} onClick={onClose}><Icon size={19}/>{label}</Link>)}<Link href="/groups" onClick={onClose}><Users size={19}/>Groups</Link><Link href="/settings" onClick={onClose}><Settings size={19}/>Settings</Link></nav></aside></>; }
export function QuickAction({href,icon,label,detail}:{href:string;icon:"message"|"group"|"spark";label:string;detail:string}) { const Icon=icon==="message"?MessageCircle:icon==="group"?Users:Compass; return <Link href={href} className={styles.quickAction}><span><Icon size={18}/></span><div><strong>{label}</strong><small>{detail}</small></div></Link>; }
export function CreatePostCard(){return <section className={styles.createCard}><div><Avatar name="You"/><textarea placeholder="Share an idea, a question, or an activity..."/></div><footer><button type="button"><ImagePlus size={17}/> Photo</button><button type="button"><Users size={17}/> Group</button><button type="button" className={styles.publish}>Publish <Send size={15}/></button></footer></section>;}
export function PostCard({post}:{post:Post}){const[liked,setLiked]=useState(false);return <article className={styles.postCard}><header><div className={styles.author}><Avatar name={post.author}/><div><strong>{post.author}</strong><span>{post.city} · {post.time}</span></div></div><span className={styles.category}>{post.category}</span></header><p>{post.text}</p><div className={`${styles.postVisual} ${styles[post.tone]}`}><span>{post.category}</span></div><div className={styles.tags}>{post.tags.map((tag)=><span key={tag}>#{tag}</span>)}</div><footer><button type="button" className={liked?styles.liked:""} onClick={()=>setLiked(!liked)}><Heart size={17}/> {post.likes+Number(liked)}</button><button type="button"><MessageCircle size={17}/> {post.comments}</button><button type="button"><Send size={17}/> {post.shares}</button></footer></article>;}
export function RightRail(){return <aside className={styles.rightRail}><section><p className={styles.sectionLabel}>Suggested people</p><h2>Make a connection</h2>{["Lina Benali","Yassine Amrani","Sara El Idrissi"].map((name)=><div key={name} className={styles.person}><Avatar name={name}/><div><strong>{name}</strong><span>2 shared interests</span></div><button type="button">Add</button></div>)}<Link href="/discover">See everyone</Link></section><section><p className={styles.sectionLabel}>Popular now</p><h2>Communities to join</h2><Link className={styles.groupLink} href="/groups">💻 Frontend Morocco <small>1.2k members</small></Link><Link className={styles.groupLink} href="/groups">🎨 Creative Morocco <small>840 members</small></Link></section></aside>;}
